---
title: "Course Textbook: Intelligent Learning Environments"
author: "Irene-Angelica Chounta"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: 
description: "Textbook for the course 'Intelligent Learning Environments' - Academic Year 2024-2025"
---

# Preface{-}

This resource aims to serve as "*classroom notes*" for the course "Intelligent Learning Environments". It does not aim to substitute other learning materials distributed during the lecture or to replace the in-person lectures. Also, this resource is **by no means** complete or exhaustive. It was put together while taking notes throughout the semester and it is meant to be updated every year.

As such, I would like to acknkowledge and thank the students who shared their own notes over time, and who provided triggers for putting everything together with their emails, questions, and suggestions.

Note: Please don't hesitate to send me feedback for improvements.

To create this learning resource, I used the R package **bookdown** - **bookdown**  can be installed from CRAN or Github:

```{r eval=FALSE}
install.packages("bookdown")
# or the development version
# devtools::install_github("rstudio/bookdown")
```

Happy readings :)
-irene

<!--chapter:end:index.Rmd-->

# Introduction {#intro}

Computers and '*machine-intelligence*' are frequently discussed as the means for addressing today's critical educational challenges: learning remotely, learning at one's own pace, learning according to one's needs and background, providing quality education to all and for all. In this course, we welcome all master-level students with technical or non-technical backgrounds. Through the semester, we will cover topics on the intersection of Artificial Intelligence in Education, Educational Technologies, and Human-Computer Interaction and we will carry out hands-on exercises to deepen our understanding of intelligent learning technologies. Specifically, we will go over the following:

- [[Learning Theories and Technologies]]  
- [[Artificial intelligence in education (AIED)]]  
- [[Student Modeling]]  
- [[Intelligent Tutoring Systems (ITS)]]
- [[Collaborative learning environments]] / [[MOOCs]]  
- [[Learning Management Systems]] / [[Open Educational Resources]]  
- [[Fairness, Accountability, Transparency, and Ethics in AIED]]

## **Learning Objectives**
Students will learn about the state-of-the-art research in Educational Technologies with a focus on Artificial Intelligence in Education. They will familiarize themselves with algorithmic techniques for modeling cognition and knowledge, and they will explore how these representations are used in practice. Students will explore various learning environments supported by "intelligent" algorithms and will learn about using technology as a tool and means for orchestrating learning.

## **Literature**
- How People Learn: Brain, Mind, Experience, and School: Expanded Edition (2000), National Research Council. [@howpeoplelearn]  
- Handbook of design in educational technology, edited by Rosemary Luckin, Sadhana Puntambekar, Peter Goodyear, Barbara Grabowski, Joshua Underwood, and Niall Winters. [@handbookedtech]  
- Selected publications (research/news articles) distributed over the duration of the course.



<!--chapter:end:01-intro.Rmd-->


# Learning Theories and Technologies {#learningtheories}

Placeholder


## How do people learn?
### Behaviourism{#behaviorism}
### Constructivism
### Social Constructivism
### Cognitivism
## Educational technology and educational technologies
## Educational Technologies and Learning Theories
## Intelligent Learning Environments
## Questions for Chapter \@ref(learningtheories)
## To-Read

<!--chapter:end:02-learning_theories.Rmd-->


# Intelligent Tutoring Systems {#its}

Placeholder


## A brief history of Intelligent Tutoring Systems
## Cognitive Tutors
### Model-tracing Tutors
### Example-tracing Tutors
### Knowledge-tracing Tutors
## Architecture of Intelligent Tutoring Systems
## Effectiveness of Intelligent Tutoring Systems
## Questions for Chapter \@ref(its)
## To-Read

<!--chapter:end:03-ITS.Rmd-->


# Student Modeling {#studentmodels}

Placeholder


## Learning Curve and Predicted Learning Curve
## Overlay Student Models
### Item-Response Theory Models
### Model-tracing Models
## Questions for Chapter \@ref(studentmodels)
## To-Read

<!--chapter:end:04-studentmodels.Rmd-->


# Collaborative Learning {#cits}

Placeholder


## Computer-Supported Collaborative Learning Environments
## Collaborative Intelligent Tutoring Systems (CITSs)
### Adaptive Collaborative Learning Support
### CITSs for Problem-based Learning
### CITSs for scripted collaboration
## Questions for Chapter \@ref(cits)
## To-Read

<!--chapter:end:05-CITS.Rmd-->


# Artificial Intelligence in Education {#aied}

Placeholder


## What is Intelligence?
## What is Artificial Intelligence?
## Artificial Intelligence in Education (AIED)
### A Bit of History
### AIED Premises
## AI Methods in Education
## FATE
### AI Bias
#### Bias due to class imbalance
#### Hidden Bias
#### Distribution Shift
### Accountability & Transparency in AI:
### Ethics and AIED
## Questions for Chapter \@ref(aied)
## To-Read

<!--chapter:end:06-AIED.Rmd-->

`r if (knitr:::is_html_output()) '
# References {-}
'`

<!--chapter:end:07-references.Rmd-->

